services:
  mongr8-mongodb:
    image: mongo
    container_name: mongr8-mongodb
    ports:
      - 27099:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongr8
      MONGO_INITDB_ROOT_PASSWORD: mongr8
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
