services:
  mongr8.mongodb.one:
    image: mongo:latest
    container_name: mongr8-mongodb-one
    ports:
      - 27117:27117
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongr8
      MONGO_INITDB_ROOT_PASSWORD: mongr8
    volumes:
      - ./data/mongodb1:/data/db
      - ./mock-mongo-keyfile:/opt/mongo-keyfile
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--port", "27117", "--keyFile", "/opt/mongo-keyfile/keyfile"]

  mongr8.mongodb.two:
    image: mongo:latest
    container_name: mongr8-mongodb-two
    ports:
      - 27118:27118
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongr8
      MONGO_INITDB_ROOT_PASSWORD: mongr8
    volumes:
      - ./data/mongodb2:/data/db
      - ./mock-mongo-keyfile:/opt/mongo-keyfile
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs", "--port", "27118", "--keyFile", "/opt/mongo-keyfile/keyfile"]
  
