{{ define "migration" }}
/*
DOT NOT EDIT, THIS FILE IS GENERATED BY CODE GEN
Create date: {{ .CreateDate}}
Created by: go-mongr8

Copyright (c) 2023 the go-mongr8 Authors and Contributors
[@see Authors file]

Licensed under the MIT License
(https://opensource.org/licenses/MIT)
*/

package migration

import (
	"github.com/amirkode/go-mongr8/collection"
	"github.com/amirkode/go-mongr8/collection/field"
	"github.com/amirkode/go-mongr8/collection/index"
	"github.com/amirkode/go-mongr8/collection/metadata"
	"github.com/amirkode/go-mongr8/migration/migrator"
	si "github.com/amirkode/go-mongr8/migration/translator/mongodb/schema_interpreter"
)

// the suffix incremented automatically
var Migration{{ .MigrationSuffix}} = {{ .Migration}}

{{ end }}