{{ define "migration" }}
/*
DOT NOT EDIT, THIS FILE WAS GENERATED BY CODE GEN
Create date: {{ .CreateDate}}
Created by: go-mongr8

Copyright (c) 2023 the go-mongr8 Authors and Contributors
[@see Authors file]

Licensed under the MIT License
(https://opensource.org/licenses/MIT)
*/

package migration

import (
	"github.com/amirkode/go-mongr8/collection"
	{{- if .UseField -}}{{"\n"}}"github.com/amirkode/go-mongr8/collection/field"{{"\n"}}{{- end -}}
	{{- if .UseIndex -}}{{"\n"}}"github.com/amirkode/go-mongr8/collection/index"{{"\n"}}{{- end -}}
	"github.com/amirkode/go-mongr8/collection/metadata"
	"github.com/amirkode/go-mongr8/migration/migrator"
	si "github.com/amirkode/go-mongr8/migration/translator/mongodb/schema_interpreter"
)

// the suffix incremented automatically
var Migration{{ .MigrationSuffix}} = {{ .Migration}}

{{ end }}

{{ define "migrations" }}
/*
DOT NOT EDIT, THIS FILE WAS GENERATED BY CODE GEN
Created by: go-mongr8
Create date: {{ .CreateDate}}

Copyright (c) 2023 the go-mongr8 Authors and Contributors
[@see Authors file]

Licensed under the MIT License
(https://opensource.org/licenses/MIT)
*/

package migration

import (
	"github.com/amirkode/go-mongr8/migration/migrator"
)

// get all migration sub action schemas
// used for define current schema of migration files
func GetAllMigrations() []migrator.Migration {
	return []migrator.Migration{
		{{ range .Migrations }}{{ . }},
		{{ end }}
	}
}
{{ end }}