{{ define "collection" }}
/*
Create date: {{ .CreateDate}}
Created by: go-mongr8

Copyright (c) 2023 the go-mongr8 Authors and Contributors
[@see Authors file]

Licensed under the MIT License
(https://opensource.org/licenses/MIT)
*/

package collection

import (
	"github.com/amirkode/go-mongr8/collection"
	"github.com/amirkode/go-mongr8/collection/metadata"
)

type {{ .Entity}} struct { }

func ({{ .Entity}}) Collection() collection.Metadata {
	return metadata.InitMetadata("{{ .Collection}}")
}

func ({{ .Entity}}) Fields() []collection.Field {
	return []collection.Field{
		// define fields here
		// examples:
		// import: "github.com/amirkode/go-mongr8/collection/field"
		// field.Int32Field("id"),
		// field.ArrayField("names").SetArrayField(field.StringField("")),
	}
}

func ({{ .Entity}}) Indexes() []collection.Index {
	return []collection.Index{
		// define indexes here
		// examples:
		// import: "github.com/amirkode/go-mongr8/collection/index"
	}
}

var Instance{{ .Entity}} collection.Collection = {{ .Entity}}{}
{{ end }}


{{ define "combined_collections" }}
/*
DOT NOT EDIT, THIS FILE WAS GENERATED BY CODE GEN
Create date: {{ .CreateDate}}
Created by: go-mongr8

Copyright (c) 2023 the go-mongr8 Authors and Contributors
[@see Authors file]

Licensed under the MIT License
(https://opensource.org/licenses/MIT)
*/

package no_edit

import (
	"github.com/amirkode/go-mongr8/collection"
	coll "{{ .ModuleName}}/mongr8/collection"
)

func GetAllCollections() []collection.Collection {
	res := []collection.Collection{
		{{ range .Collections }}coll.{{ . }},
		{{ end }}
	}

	return res
}
{{ end }}