# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:8.0
        env:
          MONGO_INITDB_ROOT_USERNAME: mongr8
          MONGO_INITDB_ROOT_PASSWORD: mongr8
        ports:
          - 27017:27017
        options: --health-cmd="mongosh --quiet mongodb://mongr8:mongr8@localhost:27017/admin --eval 'db.adminCommand({ ping: 1 }).ok'" --health-interval=5s --health-timeout=10s --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        env:
          MONGO_TEST_URI: mongodb://mongr8:mongr8@localhost:27017
        run: go test -v ./...
 